Finex the error.next/types/validator.ts(90,31): error TS2559: Type 'typeof import("/vercel/path0/sacrament-meeting/app/api/meetings/[id]/route")' has no properties in common with type 'RouteHandlerConfig<"/api/meetings/[id]">'. Failed to type check. Error: Command "npm run build" exited with 1
Changed the GET function in the meetings/[id]/route so that it isn't an default export.